### ISSUE TITLE
Insta-Plugin

### ISSUE THREAD

**Issue by gegerino** [clicktonext/kirby-product-issues#1]
Hello, is there a tutorial to set up the plugin or how I get to the appropriate Token?

**Comment by afbora** [comment]
Hey,

You can review several resources on the Internet. If you can't, we can help you via remote desktop software.

https://elfsight.com/blog/2016/05/how-to-get-instagram-access-token/
https://www.youtube.com/watch?v=uj9WpuFIZb8

**Comment by afbora** [comment]
Please let me know any help needed.
